# Introduction

In this lab assessment you will explore writing more advanced SQL queries aimed at analyzing data on a more granular level. You will be working with 3 different databases throughout the assessment.
- planets.db: Contains data pertaining to planets in our solar system
- dogs.db: Contains data pertaining to famous fictional dog characters
- babe_ruth.db: Contains data pertaining to Babe Ruth's baseball career statistics

SQL (Structured Query Language) provides powerful tools for manipulating and analyzing data in relational databases. Four key operations for working with data are filtering, ordering, limiting, and grouping. These operations can be combined in a single query to perform complex data analysis and extraction tasks, allowing for powerful and flexible data manipulation.

## Learning Objectives

* Retrieve a subset of records from a table using a WHERE clause
* Filter results using conditional operators
* Apply an aggregate function to the result of a query
* Order the results of your queries by using ORDER BY (ASC & DESC)
* Limit the number of records returned by a query using LIMIT
* Use Group BY statements in SQL to apply aggregate functions

## Part I: Basic Filtering

You will begin by looking at the planets data to perform some basic filtering queries.

Table Name: planets

In [8]:
# CodeGrade step0

# Run this cell without changes

import pandas as pd
import sqlite3

# Create the connection
# Note the connect is 'conn1' since there will be multiple .db used
conn1 = sqlite3.connect('planets.db')

# Select all
pd.read_sql("""SELECT * FROM planets; """, conn1)

   id     name       color  num_of_moons    mass  rings
0   1  Mercury        gray             0    0.55      0
1   2    Venus      yellow             0    0.82      0
2   3    Earth        blue             1    1.00      0
3   4     Mars         red             2    0.11      0
4   5  Jupiter      orange            68  317.90      0
5   6   Saturn       hazel            62   95.19      1
6   7   Uranus  light blue            27   14.54      1
7   8  Neptune   dark blue            14   17.15      1

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn1)

Empty DataFrame
Columns: [name]
Index: []

### Step 1
Return all the columns for planets that have 0 moons.

In [1]:
import os
os.listdir()

['.config', 'sample_data']

In [3]:
from google.colab import files
uploaded = files.upload()

Saving babe_ruth.db to babe_ruth.db

In [4]:
from google.colab import files
uploaded = files.upload()

Saving dogs.db to dogs.db

In [5]:
from google.colab import files
uploaded = files.upload()

Saving planets.db to planets (1).db

In [6]:
import os
os.listdir()

['.config',
 'dogs.db',
 'planets (1).db',
 'babe_ruth.db',
 'planets.db',
 'sample_data']

In [7]:
os.remove("planets (1).db")

In [11]:
# CodeGrade step1
# Replace None with your code

df_no_moons = pd.read_sql("""
SELECT *
FROM planets
WHERE num_of_moons = 0;
""", conn1)

df_no_moons

   id     name   color  num_of_moons  mass  rings
0   1  Mercury    gray             0  0.55      0
1   2    Venus  yellow             0  0.82      0

In [10]:
pd.read_sql("""
PRAGMA table_info(planets);
""", conn1)

   cid          name     type  notnull dflt_value  pk
0    0            id  INTEGER        0       None   1
1    1          name     TEXT        0       None   0
2    2         color     TEXT        0       None   0
3    3  num_of_moons  INTEGER        0       None   0
4    4          mass     REAL        0       None   0
5    5         rings  BOOLEAN        0       None   0

### Step 2
Return the name and mass of each planet that has a name with exactly 7 letters. Avoid hard coding this filter subset as much as possible.

In [12]:
# CodeGrade step2
# Replace None with your code

df_name_seven = pd.read_sql("""
SELECT name, mass
FROM planets
WHERE LENGTH(name) = 7;
""", conn1)

df_name_seven

      name    mass
0  Mercury    0.55
1  Jupiter  317.90
2  Neptune   17.15

## Part 2: Advanced Filtering

### Step 3

Return the name and mass for each planet that has a mass that is less than or equal to 1.00.

In [13]:
# CodeGrade step3
# Replace None with your code

df_mass = pd.read_sql("""
SELECT name, mass
FROM planets
WHERE mass <= 1.00;
""", conn1)

df_mass

      name  mass
0  Mercury  0.55
1    Venus  0.82
2    Earth  1.00
3     Mars  0.11

### Step 4

Return all the columns for planets that have at least one moon and a mass less than 1.00.

In [14]:
# CodeGrade step4
# Replace None with your code

df_mass_moon = pd.read_sql("""
SELECT *
FROM planets
WHERE num_of_moons >= 1
AND mass < 1.00;
""", conn1)

df_mass_moon

   id  name color  num_of_moons  mass  rings
0   4  Mars   red             2  0.11      0

### Step 5

Return the name and color of planets that have a color containing the string "blue".

In [15]:
# CodeGrade step5
# Replace None with your code

df_blue = pd.read_sql("""
SELECT name, color
FROM planets
WHERE color LIKE '%blue%';
""", conn1)

df_blue

      name       color
0    Earth        blue
1   Uranus  light blue
2  Neptune   dark blue

## Part 3: Ordering and Limiting

This database has some fictional, yet generally famous, dogs.

Table Name: dogs

In [16]:
# CodeGrade step0

# Run this cell without changes

# Create a connection
# Note the connect is 'conn2' since they will be multiple .db used
conn2 = sqlite3.connect('dogs.db')

# Select all
pd.read_sql("SELECT * FROM dogs;", conn2)

   id        name  age gender             breed  temperament  hungry
0   1      Snoopy    3      M            beagle     friendly       1
1   2     McGruff   10      M        bloodhound        aware       0
2   3      Scooby    6      M        great dane       hungry       1
3   4  Little Ann    5      F         coonhound        loyal       0
4   5     Pickles   13      F         black lab  mischievous       1
5   6    Clifford    4      M           big red       smiley       1
6   7      Lassie    7      F            collie       loving       1
7   8       Snowy    8      F       fox terrier  adventurous       0
8   9        None    4      M  golden retriever      playful       1

### Step 6
Return the name, age, and breed of all dogs that are hungry (binary flag of 1) and sort them from youngest to oldest.

In [18]:
# CodeGrade step6
# Replace None with your code

df_hungry = pd.read_sql("""
SELECT name, age, breed
FROM dogs
WHERE hungry = 1
ORDER BY age ASC;
""", conn2)

df_hungry

       name  age             breed
0    Snoopy    3            beagle
1  Clifford    4           big red
2      None    4  golden retriever
3    Scooby    6        great dane
4    Lassie    7            collie
5   Pickles   13         black lab

In [17]:
conn2 = sqlite3.connect('dogs.db')

### Step 7
Return the name, age, and hungry columns for hungry dogs between the ages of two and seven. This query should also sort these dogs in alphabetical order.

In [19]:
# CodeGrade step7
# Replace None with your code

df_hungry_ages = pd.read_sql("""
SELECT name, age, hungry
FROM dogs
WHERE hungry = 1
AND age BETWEEN 2 AND 7
ORDER BY name ASC;
""", conn2)

df_hungry_ages

       name  age  hungry
0      None    4       1
1  Clifford    4       1
2    Lassie    7       1
3    Scooby    6       1
4    Snoopy    3       1

### Step 8

Return the name, age, and breed for the 4 oldest dogs. Sort the result alphabetically based on the breed.

In [20]:
# CodeGrade step8
# Replace None with your code

df_4_oldest = pd.read_sql("""
SELECT name, age, breed
FROM dogs
ORDER BY age DESC
LIMIT 4;
""", conn2)

df_4_oldest = df_4_oldest.sort_values(by='breed')

df_4_oldest

      name  age        breed
0  Pickles   13    black lab
1  McGruff   10   bloodhound
3   Lassie    7       collie
2    Snowy    8  fox terrier

## Part 4: Aggregation

In the next few parts, you'll query data from a table populated with Babe Ruth's career hitting statistics. You'll use aggregate functions to pull interesting information from the table that basic queries cannot track.

Table Name: babe_ruth_stats

In [21]:
# CodeGrade step0

# Run this cell without changes

# Create a connection
# Note the connect is 'conn3' since they will be multiple .db used
conn3 = sqlite3.connect('babe_ruth.db')

# Select all
pd.read_sql("""
SELECT * FROM babe_ruth_stats; """, conn3)

,id,year,team,league,doubles,triples,hits,HR,games,runs,RBI,at_bats,BB,SB,SO,AVG
0,1,1914,BOS,AL,1,0,2,0,5,1,2,10,0,0,4,0.200
1,2,1915,BOS,AL,10,1,29,4,42,16,21,92,9,0,23,0.315
2,3,1916,BOS,AL,5,3,37,3,67,18,15,136,10,0,23,0.272
3,4,1917,BOS,AL,6,3,40,2,52,14,12,123,12,0,18,0.325
4,5,1918,BOS,AL,26,11,95,11,95,50,66,317,58,6,58,0.300
5,6,1919,BOS,AL,34,12,139,29,130,103,114,432,101,7,58,0.322
6,7,1920,NY,AL,36,9,172,54,142,158,137,458,150,14,80,0.376
7,8,1921,NY,AL,44,16,204,59,152,177,171,540,145,17,81,0.378
8,9,1922,NY,AL,24,8,128,35,110,94,99,406,84,2,80,0.315
9,10,1923,NY,AL,45,13,205,41,152,151,131,522,170,17,93,0.393
10,11,1924,NY,AL,39,7,200,46,153,143,121,529,142,9,81,0.378
11,12,1925,NY,AL,12,2,104,25,98,61,66,359,59,2,68,0.290
12,13,1926,NY,AL,30,5,184,47,152,139,146,495,144,11,76,0.372
13,14,1927,NY,AL,29,8,192,60,151,158,164,540,137,7,89,0.356
14,15,1928,NY,AL,29,8,173,54,154,163,142,536,137,4,87,0.323
15,16,1929,NY,AL,26,6,172,46,135,121,154,499,72,5,60,0.345
16,17,1930,NY,AL,28,9,186,49,145,150,153,518,136,10,61,0.359
17,18,1931,NY,AL,31,3,199,46,145,149,163,534,128,5,51,0.373
18,19,1932,NY,AL,13,5,156,41,133,120,137,457,130,2,62,0.341
19,20,1933,NY,AL,21,3,138,34,137,97,103,459,114,4,90,0.301
20,21,1934,NY,AL,17,4,105,22,125,78,84,365,104,1,63,0.288
21,22,1935,BOS,NL,0,0,13,6,28,13,12,72,20,0,24,0.181

### Step 9

Return the total number of years that Babe Ruth played professional baseball

In [26]:
# CodeGrade step9
# Replace None with your code

df_ruth_years = pd.read_sql("""
SELECT COUNT(DISTINCT year) AS total_years
FROM babe_ruth_stats;
""", conn3)

df_ruth_years

   total_years
0           22

In [25]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn3)

              name
0  babe_ruth_stats

In [23]:
conn3 = sqlite3.connect('babe_ruth.db')

### Step 10

Return the total number of homeruns hit by Babe Ruth during his career.

In [29]:
# CodeGrade step10
# Replace None with your code

df_hr_total = pd.read_sql("""
SELECT SUM(HR) AS total_homeruns
FROM babe_ruth_stats;
""", conn3)

df_hr_total

   total_homeruns
0             714

In [28]:
pd.read_sql("""
PRAGMA table_info(babe_ruth_stats);
""", conn3)

    cid     name     type  notnull dflt_value  pk
0     0       id  INTEGER        0       None   1
1     1     year  INTEGER        0       None   0
2     2     team     TEXT        0       None   0
3     3   league     TEXT        0       None   0
4     4  doubles  INTEGER        0       None   0
5     5  triples  INTEGER        0       None   0
6     6     hits  INTEGER        0       None   0
7     7       HR  INTEGER        0       None   0
8     8    games  INTEGER        0       None   0
9     9     runs  INTEGER        0       None   0
10   10      RBI  INTEGER        0       None   0
11   11  at_bats  INTEGER        0       None   0
12   12       BB  INTEGER        0       None   0
13   13       SB  INTEGER        0       None   0
14   14       SO  INTEGER        0       None   0
15   15      AVG     REAL        0       None   0

## Part 5: Grouping and Aggregation

### Step 11

For each team that Babe Ruth has played on, return the team name and the number of years he played on that team, aliased as 'number_years'.

In [30]:
# CodeGrade step11
# Replace None with your code

df_teams_years = pd.read_sql("""
SELECT team,
COUNT(DISTINCT year) AS number_years
FROM babe_ruth_stats
GROUP BY team;
""", conn3)

df_teams_years

  team  number_years
0  BOS             7
1   NY            15

### Step 12

For each team that Babe Ruth played on and averged over 200 at bats with, return the team name and average number of at bats, aliased as 'average_at_bats'.

In [31]:
# CodeGrade step12
# Replace None with your code

df_at_bats = pd.read_sql("""
SELECT team,
AVG(at_bats) AS average_at_bats
FROM babe_ruth_stats
GROUP BY team
HAVING AVG(at_bats) > 200;
""", conn3)

df_at_bats

  team  average_at_bats
0   NY       481.133333

#### Close the connections

In [32]:
# Run this cell without changes

conn1.close()
conn2.close()
conn3.close()